### ISSUE TITLE
Storybook Not building, when adding 'sass' and '.modules.scss'

### ISSUE THREAD

**Issue by pijusz** [Lukazovic/nextjs-with-chakra-ui-boilerplate#1]
Hi,

I wanted to add some custom CSS to my project and my favorite setup is having scss in component folders. But I cant make it work. Do you have any ideas how to fix it?

**Comment by Lukazovic** [comment]
Hi @pijusz,

Sorry for the delay to get back to you.

I haven't tried to use `sass` and `.modules.scss` on Storybook + Next + Chakra-ui yet. I can try it out tho.

But since chakra-ui uses [`emotion`](https://emotion.sh/docs/introduction) to create components, when I have to create custom styles in chakra-ui I usually create a styled-component. For example:

![Screenshot from 2021-10-06 19-01-20](https://user-images.githubusercontent.com/54550926/136289640-93c0ddea-10f9-47f2-8612-847db84c665f.png)
